<?php
/**
 * OrderItem.php
 * @author liuchg
 */

namespace common\models\order;

use yii\db\ActiveRecord;

/**
 * Class OrderItem
 * @package common\models\order
 * @property int $id
 * @property int $order_id
 * @property int $product_id
 * @property int $product_sku_id 对应商品 SKU ID
 * @property int $amount 数量
 * @property int $price 单价
 * @property int $rating 用户打分
 * @property int $review 用户评价
 * @property int $reviewed_at 评价时间
 */
class OrderItem extends ActiveRecord
{
    public static function tableName()
    {
        return 'order_item'; // TODO: Change the autogenerated stub
    }
}