<?php
/**
 * ProductSku.php
 * @author liuchg
 */

namespace common\models\produce;


use yii\db\ActiveRecord;

/**
 * 表 product_sku
 * @package common\models\produce
 * @property int $id
 * @property int $product_id
 * @property int $title sku名称
 * @property int $description sku描述
 * @property int $price 价格
 * @property int $stock 库存
 */
class ProductSku extends ActiveRecord
{
    public static function tableName()
    {
        return 'product_sku'; // TODO: Change the autogenerated stub
    }
}